/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yczhang' at '6/6/17 11:31 AM' with Gradle 2.14.1
 *
 * @author yczhang, @date 6/6/17 11:31 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
